name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@v3.21.2
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DUNCAT_BUILD_TESTS=ON -DUNCAT_BUILD_EXAMPLES=ON ..
        cmake --build . --config Debug -j 4
