name: Build (ubuntu)

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - uses: tj-actions/changed-files@v40
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","

    - uses: DavidAnson/markdownlint-cli2-action@v14
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","

  build-debug:
    needs: [ markdownlint ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@v3.27.0

    - name: CMake Configure
      run: |
        mkdir build
        cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUNCAT_BUILD_TESTS=ON -DUNCAT_BUILD_EXAMPLES=ON

    - uses: cpp-linter/cpp-linter-action@v2
      id: format
      with:
        database: 'build'
        style: file
        tidy-checks: ''
        version: 16

    - name: Test Failure
      if: steps.format.outputs.checks-failed > 0
      run: echo "Some files failed the linting checks!" && exit 1

    - name: CMake Build
      run: cmake --build build --config Debug -j 4
