name: Markdown lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  markdownlint-on-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - uses: tj-actions/changed-files@v40
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","

    - uses: DavidAnson/markdownlint-cli2-action@v14
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
